stages:
- push

services:
- docker:dind

push:
  image: docker:latest
  stage: push
  script:
    - echo ${EL_REGISTRY_USER}
    - echo ${EL_REGISTRY_PASSWORD}
    - docker info
    - docker login -u "${EL_REGISTRY_USER}" -p "${EL_REGISTRY_PASSWORD}" repohub.enterpriselab.ch:5002
    - docker build -t naoqi-dev:latest .
    - docker tag naoqi-dev repohub.enterpriselab.ch:5002/kawa/naoqi-dev:latest
    - docker push repohub.enterpriselab.ch:5002/kawa/naoqi-dev:latest
    - docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASSWORD}"
    - docker tag naoqi-dev "${DOCKERHUB_USER}"/naoqi-opencv-developer:latest
    - docker push "${DOCKERHUB_USER}"/naoqi-opencv-developer:latest
